### ISSUE TITLE
Proxy error httpx

### ISSUE THREAD

**Issue by Local22221** [deepjyoti30/ytmdl#308]
# Bug report
## Version Info

- Ytmdl version: `2024.08.15.1`
- Youtube-dl version: `PUT VERSION HERE`

## How Ytmdl was installed?
pip
## Console Log

```console

Traceback (most recent call last):
C:\Users\Lockie>ytmdl Hello
 ==> Searching to see if already present in C:\Users\Lockie\Music
 ==> Searching Youtube for Hello
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Lockie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\ytmdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Lockie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\ytmdl\main.py", line 614, in entry
    extract_data()
  File "C:\Users\Lockie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\ytmdl\main.py", line 609, in extract_data
    main(args)
  File "C:\Users\Lockie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\ytmdl\main.py", line 275, in main
    link, yt_title = search(song_name=song_name, args=args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lockie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\ytmdl\core.py", line 52, in search
    data = yt.search(song_name, not args.disable_metaadd,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lockie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\ytmdl\yt.py", line 264, in search
    results = VideosSearch(query, limit=lim).result()["result"]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lockie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\youtubesearchpython\search.py", line 148, in __init__
    self.sync_create()
  File "C:\Users\Lockie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\youtubesearchpython\core\search.py", line 29, in sync_create
    self._makeRequest()
  File "C:\Users\Lockie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\youtubesearchpython\core\search.py", line 51, in _makeRequest
    request = self.syncPostRequest()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lockie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\youtubesearchpython\core\requests.py", line 20, in syncPostRequest
    return httpx.post(
           ^^^^^^^^^^^
TypeError: post() got an unexpected keyword argument 'proxies'```

## Description
Reinstalled twice, not very experienced with programming stuff, ytmdl fails when trying to download music. The error occurs when I try to search for a song, and it appears to be related to a TypeError with the httpx.post(). The error message states that an unexpected keyword argument proxies was passed. How do I fix this?

**Comment by CarloDePieri** [comment]
I can confirm this.

Arch linux
python: `3.13.1`
ytmdl: `2024.08.15.1` (installed from the Aur repo, see the [PKGBUILD here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ytmdl); I even tried directly from pip in a venv with no luck)
yt-dlp: `2025.01.26` (installed from the Arch repo, it works on its own)

**Comment by Local22221** [comment]
I fixed it myself! You have to downgrade httpx to version 0.27! see https://stackoverflow.com/questions/79277656/error-post-got-an-unexpected-keyword-argument-proxies

**Comment by Local22221** [comment]
> I can confirm this.
> 
> Arch linux python: `3.13.1` ytmdl: `2024.08.15.1` (installed from the Aur repo, see the [PKGBUILD here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ytmdl); I even tried directly from pip in a venv with no luck) yt-dlp: `2025.01.26` (installed from the Arch repo, it works on its own)

Yep, solution below, Case closed.

**Comment by CarloDePieri** [comment]
> > I can confirm this.
> > Arch linux python: `3.13.1` ytmdl: `2024.08.15.1` (installed from the Aur repo, see the [PKGBUILD here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ytmdl); I even tried directly from pip in a venv with no luck) yt-dlp: `2025.01.26` (installed from the Arch repo, it works on its own)
> 
> Yep, solution below, Case closed.

Good job finding the breaking dependency update.
Pinning `httpx<0.28` is definitely not fixing the problem though, it's barely a workaround.

The core problem is the dependency on a library which has been archived since mid '22. We need at least to pin `httpx` for the time being.

**Comment by sam1425** [comment]
for pipx installs
`pipx runpip ytmdl install --force-reinstall 'httpx<0.28'`

**Comment by ghost** [comment]
I am suffering from the same issue, was trying to port ytmdl for FreeBSD Platform. I think it's not possible to use older version of a package in FreeBSD. The current httpx version is 0.28.1 for FreeBSD.

**Comment by NoamLeshem** [comment]
hi, found a solution here **(not needing to downgrade the httpx package)**:
https://github.com/Shakabrahh/youtube-search-python/commit/842d6e37f479c9c49234511f7980a69f4f2bbd3f
making those changes worked for me

please let me know if it also worked for you (or not)

**Comment by ShivaPrakash-006** [comment]
@NoamLeshem somehow it does work. I did make a backup before changing the file tho. I advise anyone who finds this to do the same.

**Comment by CarloDePieri** [comment]
> hi, found a solution here **(not needing to downgrade the httpx package)**: [Shakabrahh/youtube-search-python@842d6e3](https://github.com/Shakabrahh/youtube-search-python/commit/842d6e37f479c9c49234511f7980a69f4f2bbd3f) making those changes worked for me
> 
> please let me know if it also worked for you (or not)

I mean... I don't know this codebase enough, but wouldn't these changes break proxies support?
The new version of httpx probably handles them in a different way, so even if by not using the old api it's not crashing anymore, we should interact with their new api to really fix this.

**Comment by ShivaPrakash-006** [comment]
> I mean... I don't know this codebase enough, but wouldn't these changes break proxies support?
> The new version of httpx probably handles them in a different way, so even if by not using the old api it's not crashing anymore, we should interact with their new api to really fix this.

It does break proxy support, we just have to wait for the dependencies to update to the new version of httpx unfortunately
